# Generated by Django 4.2.6 on 2023-10-18 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThemesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_celebration_mode.events')),
            ],
        ),
    ]
