# Generated by Django 4.2.6 on 2023-10-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_celebration_mode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Eventss',
        ),
    ]
